cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<movie_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<movie_id>\d+)/$', views.cart_remove, name='cart_remove'),
    url(r'^clear/$', views.cart_clear, name='cart_clear'),

]

movies/urls.py
from django.conf.urls import url

from . import views

app_name = 'movies'

# Regexes of all of the views. The first regex to match the url is then used
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sort_name_asc/$', views.sort_name_asc, name='sort_name_asc'),
    url(r'^sort_name_dsc/$', views.sort_name_dsc, name='sort_name_dsc'),
    url(r'^sort_price_asc/$', views.sort_price_asc, name='sort_price_asc'),
    url(r'^sort_price_dsc/$', views.sort_price_dsc, name='sort_price_dsc'),
    url(r'^sort_date_asc/$', views.sort_date_asc, name='sort_date_asc'),
    url(r'^sort_date_dsc/$', views.sort_date_dsc, name='sort_date_dsc'),
    url(r'^upload/$', views.movie_upload, name='movie_upload'),
    url(r'^(?P<movie_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create_movie/$', views.create_movie, name='create_movie'),
    url(r'^(?P<movie_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^like/$', views.like_movie, name='like_movie'),
    url(r'^dislike/$', views.dislike_movie, name='dislike_movie'),

    url(r'^$', views.review_list, name='review_list'),
    url(r'^movie/(?P<movie_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^recommendation/$', views.user_recommendation_list, name='user_recommendation_list'),

    # ex: /review/5/
    # url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),

    url(r'^(?P<genre_slug>[-\w]+)/$', views.index, name = 'movie_list_by_genre'),


]

notflix/urls.py
"""The master router for the whole project
"""

from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from adminplus.sites import AdminSitePlus

# Admin setup
admin.site = AdminSitePlus()
admin.autodiscover()


urlpatterns = [
    url(r'^notflixadmin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^stats/', include('stats.urls', namespace='stats')),
    url(r'^', include('movies.urls', namespace='movies')),
   #url(r'^users/', include('users.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'


urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

testImport/testImport/urls.py
from django.conf.urls import url
from django.contrib import admin
from adminplus.sites import AdminSitePlus

# Admin setup
admin.site = AdminSitePlus()
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

cart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    #quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
    #                                  coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from movies.models import Movie
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, movie_id):
    cart = Cart(request)
    movie = get_object_or_404(Movie, id=movie_id)
    form = CartAddProductForm(request.POST)

    # if movie_id in cart.cart.get(movie_id):
    #     return redirect('cart:cart_detail')

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(movie=movie)
                 #quantity=cd['quantity'],
                 #update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, movie_id):
    cart = Cart(request)
    movie = get_object_or_404(Movie, id=movie_id)
    cart.remove(movie)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    #for item in cart:
    #    item['update_quantity_form'] = CartAddProductForm(initial={#'quantity': item['quantity'],
    #                                                               'update': True})
    return render(request, 'cart/detail.html', {'cart': cart, 'cartlength': len(cart)})

def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')

cart/templates/cart/detail.html
{% extends "movies/base.html" %}
{% load static %}
{% block title %} Your shopping cart {% endblock %}

{% block body %}
    {% if cartlength %}

        <h1>Your shopping cart</h1>
        <table class="cart">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Movie Title</th>
                    <th>Remove</th>
    {#                <th>Unit price</th>                #}
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with movie=item.movie %}

                <tr>
                    <td>
                        <a href="{{ movie.get_absolute_url }}">
                            <img id="cart-img" src="https://placeimg.com/640/480/any?cache={{ movie.id }}" >
    {#                        <img src="{% if movie.image %}{{ movie.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">#}
                        </a>
                    </td>
                    <td>{{ movie.movie_title }}</td>

                    <td><a href="{% url "cart:cart_remove" movie.id %}">Remove</a></td>
                    <td class="num">£{{ item.price }}</td>
    {#                <td class="num">£{{ item.total_price }}</td>#}
                </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Total</td>
                <td colspan="2"></td>
                <td class="num">£{{ cart.get_total_price }}</td>
            </tr>
            </tbody>
        </table>
    {% else %}
        <h1>Your shopping cart is empty.</h1>
    {% endif %}

    <form action="{% url "movies:index" %}" method="post">
        {% csrf_token %}
        <button id="cart-btn" type="submit" value="Continue Shopping" class="btn #f44336 red"><i class="material-icons">shopping_cart</i>Continue Shopping</button>
    </form>

    {% if cart %}
    <form action="{% url "orders:order_create" %}" method="post">
        {% csrf_token %}
        <button id="cart-btn" type="submit" value="Checkout" class="btn #f44336 red"><i class="material-icons">shop</i>Checkout</button>
    </form>

        <form action="{% url "cart:cart_clear" %}" method="post">
        {% csrf_token %}
        <button id="cart-btn" type="submit" value="Clear" class="btn #f44336 red"><i class="material-icons">remove_shopping_cart</i>Clear Cart</button>
    </form>
    {% endif %}

{% endblock %}