cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<movie_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<movie_id>\d+)/$', views.cart_remove, name='cart_remove'),
    url(r'^clear/$', views.cart_clear, name='cart_clear'),

]

movies/urls.py
from django.conf.urls import url

from . import views

app_name = 'movies'

# Regexes of all of the views. The first regex to match the url is then used
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sort_name_asc/$', views.sort_name_asc, name='sort_name_asc'),
    url(r'^sort_name_dsc/$', views.sort_name_dsc, name='sort_name_dsc'),
    url(r'^sort_price_asc/$', views.sort_price_asc, name='sort_price_asc'),
    url(r'^sort_price_dsc/$', views.sort_price_dsc, name='sort_price_dsc'),
    url(r'^sort_date_asc/$', views.sort_date_asc, name='sort_date_asc'),
    url(r'^sort_date_dsc/$', views.sort_date_dsc, name='sort_date_dsc'),
    url(r'^upload/$', views.movie_upload, name='movie_upload'),
    url(r'^(?P<movie_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create_movie/$', views.create_movie, name='create_movie'),
    url(r'^(?P<movie_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^like/$', views.like_movie, name='like_movie'),
    url(r'^dislike/$', views.dislike_movie, name='dislike_movie'),

    url(r'^$', views.review_list, name='review_list'),
    url(r'^movie/(?P<movie_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^recommendation/$', views.user_recommendation_list, name='user_recommendation_list'),

    # ex: /review/5/
    # url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),

    url(r'^(?P<genre_slug>[-\w]+)/$', views.index, name = 'movie_list_by_genre'),


]

notflix/urls.py
"""The master router for the whole project
"""

from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from adminplus.sites import AdminSitePlus

# Admin setup
admin.site = AdminSitePlus()
admin.autodiscover()


urlpatterns = [
    url(r'^notflixadmin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^stats/', include('stats.urls', namespace='stats')),
    url(r'^', include('movies.urls', namespace='movies')),
   #url(r'^users/', include('users.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testImport/testImport/urls.py
from django.conf.urls import url
from django.contrib import admin
from adminplus.sites import AdminSitePlus

# Admin setup
admin.site = AdminSitePlus()
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

users/urls.py
"""Authenitcation URLs
"""

from django.conf.urls import url, include
from . import views
from . import views as core_views
from django.contrib.auth import views as auth_views
from django.urls import reverse

app_name = 'users'

urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^signup/$', core_views.signup_view, name='signup'),
    url(r'^details/$', views.detail_view, name='details'),
    url(r'^password/$', views.change_password, name='change_password'),

]

movies/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm, Textarea
from movies.models import Review

from .models import Movie


class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = ['movie_title', 'genre', 'movie_logo', 'description', 'release_date']

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
        }

movies/views.py
import csv, io
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render, get_object_or_404
from .forms import MovieForm, ReviewForm
from .models import Movie, Genre, Like, Dislike, Review
from django.db.models import Q
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from cart.forms import CartAddProductForm
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from django.contrib.auth.models import User
from django.template import RequestContext, Context
from .recommendation import *
from django.shortcuts import render_to_response

from users.models import User
import datetime
from orders.models import OrderItem

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def create_movie(request):
    """View used with movie creation

    Arguments:
        request {obj} -- The request

    Returns:
        render -- Either the movie creation page or the movie details depending
                  on whether the movie has already been created or not
    """

    # Create a form for creating a movie
    form = MovieForm(request.POST or None, request.FILES or None)
    # Check if the submitted form is valid
    if form.is_valid():
        # If it is, take appropriate measures
        movie = form.save(commit=False)
        # movie.user = request.user
        movie.movie_logo = request.FILES['movie_logo']

        file_type = movie.movie_logo.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in IMAGE_FILE_TYPES:
            context = {
                'movie': movie,
                'form': form,
                'error_message': 'Image file must be PNG, JPG, or JPEG',
            }
            return render(request, 'movies/create_movie.html', context)
        movie.save()
        return render(request, 'movies/detail.html', {'movie': movie})
    context = {
        "form": form,
    }
    # If the form isn't valid, ie get request, serve the form.
    return render(request, 'movies/create_movie.html', context)


@login_required(login_url="/users/login")
def detail(request, movie_id):
    """View showing details of a movie. The user must be logged in

    Arguments:
        request {obj} -- The request
        movie_id {int} -- The primary key of the movie queried

    Returns:
        render -- The details of the movie
    """

    movie = get_object_or_404(Movie, pk=movie_id)
    cart_movie_form = CartAddProductForm()
    is_liked = False
    is_disliked = False

    if Like.objects.filter(user=request.user.id, movie=movie).exists():
        is_liked = True
        is_disliked = False

    if Dislike.objects.filter(user=request.user.id, movie=movie).exists():
        is_disliked = True
        is_liked = False
    return render(request, 'movies/detail.html', {'movie': movie,
                                                  'is_liked': is_liked,
                                                  'is_disliked': is_disliked,
                                                  'total_likes': Like.objects.filter(movie=movie).count(),
                                                  'total_dislikes': Dislike.objects.filter(movie=movie).count(),
                                                  'cart_movie_form': cart_movie_form})


def index(request, genre_slug=None):
    """Directory of the site

    Arguments:
        request {request} -- The request

    Returns:
        render -- The home page
    """

    genre = None
    genres = Genre.objects.all()
    movies = recommend(request)
    query = request.GET.get('q')

    page = request.GET.get('page', 1)

    paginator = Paginator(movies, 10)

    try:
        if genre_slug:
            genre = get_object_or_404(Genre, slug=genre_slug)
            movies = movies.filter(genre=genre)

            return render(request, 'movies/index.html', {'genre': genre,
                                                         'genres': genres,
                                                         'movies': movies})

        if query:
            movies = movies.filter(
                Q(movie_title__icontains=query)
            ).distinct() or movies.filter(Q(description__icontains=query)).distinct() \
                     or movies.filter(Q(genre__genre__icontains=query)).distinct() \
                     or movies.filter(Q(release_date__icontains=query)).distinct()

            return render(request, 'movies/index.html', {
                'movies': movies,
            })
        movies = paginator.page(page)
    except PageNotAnInteger:
        movies = paginator.page(1)
    except EmptyPage:
        movies = paginator.page(paginator.num_pages)

    else:
        return render(request, 'movies/index.html', {'genre': genre,
                                                     'genres': genres,
                                                     'movies': movies})


def sort_name_asc(request):
    genre = None
    genres = Genre.objects.all()
    movies = Movie.objects.order_by("movie_title")
    return render(request, 'movies/index.html', {'genre': genre,
                                                 'genres': genres,
                                                 'movies': movies})


def sort_name_dsc(request):
    genre = None
    genres = Genre.objects.all()
    movies = Movie.objects.order_by("-movie_title")
    return render(request, 'movies/index.html', {'genre': genre, 'genres': genres, 'movies': movies})


def sort_price_asc(request):
    genre = None
    genres = Genre.objects.all()
    movies = Movie.objects.order_by("price")
    return render(request, 'movies/index.html', {'genre': genre, 'genres': genres, 'movies': movies})


def sort_price_dsc(request):
    genre = None
    genres = Genre.objects.all()
    movies = Movie.objects.order_by("-price")
    return render(request, 'movies/index.html', {'genre': genre, 'genres': genres, 'movies': movies})


def sort_date_asc(request):
    genre = None
    genres = Genre.objects.all()
    movies = Movie.objects.order_by("release_date")
    return render(request, 'movies/index.html', {'genre': genre, 'genres': genres, 'movies': movies})


def sort_date_dsc(request):
    genre = None
    genres = Genre.objects.all()
    movies = Movie.objects.order_by("-release_date")
    return render(request, 'movies/index.html', {'genre': genre, 'genres': genres, 'movies': movies})


# @permission_required('admin.can.add_log_entry')
def movie_upload(request):
    template = 'movies/movie_upload.html'

    prompt = {
        'order': 'Order of csv should be first name, last name, email and ip address'
    }
    if request.method == "GET":
        return render(request, template)

    csv_file = request.FILES['file']
    # check if it's a csv
    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'Not a csv file')

    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    next(io_string)
    for column in csv.reader(io_string, delimiter=',', quotechar="|"):
        _, created = Movie.objects.update_or_create(  # contact is the model

            #  "genre", "movie_title", "movie_logo", "id", "description", "release_date", "price"
            genre=column[0],
            movie_title=column[1],
            movie_logo=column[2],
            id=column[3],
            description=column[4],
            release_date=column[5],
            price=column[6]

        )

        context = {}
        return render(request, template, context)


def recommend(request):
    """Dummy recommendation algorithm which returns random movies

    -------- THIS IS NOT A VIEW --------

    Arguments:
        request {obj} -- request information for recommendation
    """

    movies = Movie.objects.order_by('?')
    return movies


def favorite(request, movie_id):
    """The view that handles the user favourite request

    Arguments:
        request {obj} -- The request
        movie_id {int} -- The id of the movie to favourite

    Returns:
        JsonResponse -- A response back to the web page
    """

    movie = get_object_or_404(Movie, pk=movie_id)
    try:
        if movie.liked:
            movie.liked = False
        else:
            movie.liked = True
        movie.save()
    except (KeyError, Movie.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def like_movie(request):
    """The view that handles the user liking the movie

    Arguments:
        request {obj} -- The request

    Returns:
        HttpResponseRedirect -- Redirect to the liked movie
    """

    movie = get_object_or_404(Movie, id=request.POST.get('movie_id'))
    is_liked = False
    if Like.objects.filter(user=request.user, movie=movie).exists():
        Like.objects.get(user=request.user, movie=movie).delete()
        is_liked = False
    else:
        new = Like(user=request.user, movie=movie)
        new.save()
        if Dislike.objects.filter(user=request.user, movie=movie).count():
            Dislike.objects.get(user=request.user, movie=movie).delete()
        is_liked = True
    return HttpResponseRedirect(movie.get_absolute_url())


def dislike_movie(request):
    """The view that handles the user disliking the movie

    Arguments:
        request {obj} -- The request

    Returns:
        HttpResponseRedirect -- Redirect to the disliked movie
    """

    movie = get_object_or_404(Movie, id=request.POST.get('movie_id'))
    is_disliked = False
    if Dislike.objects.filter(user=request.user, movie=movie).exists():
        Dislike.objects.get(user=request.user, movie=movie).delete()
        is_disliked = False
    else:
        new = Dislike(user=request.user, movie=movie)
        new.save()
        if Like.objects.filter(user=request.user, movie=movie).count():

movies/templates/movies/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Notflix{% endblock %}</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'movies/css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'movies/css/materialize.min.css' %}"/>
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    
    
    
</head>
<body>
    <nav>
        <div class="nav-wrapper grey darken-4">
            <a href="{% url 'movies:index' %}" class="brand-logo"><img class="brand-logo" src="{% static 'movies/img/logo.png' %}" alt=""></a>
            <a href="#" data-target="mobile-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">

                <li><a href="{% url 'movies:user_recommendation_list' %}">Movie suggestions</a></li>

                <li>
                    {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                    
                    <a href={% url 'cart:cart_detail' %}>
                        {{ total_items }} item{{ total_items|pluralize }}, £{{ cart.get_total_price }}
                    </a>
                    {% else %}
                    <a href={% url 'cart:cart_detail' %}>
                        <i class="material-icons">shopping_cart</i>
                    </a>
                    {% endif %}
                    {% endwith %}
                </li>
                <li>
                    <form class="navbar-form navbar-left search white-text" role="search" method="get" action="{% url 'movies:index' %}">
                        <div>
                            <input type="text" name="q" value="{{ request.GET.q }}" style="color: white;" placeholder="Search" />
                        </div>
                        <!-- <button type="submit" class="btn btn-default">Search</button>-->
                    </form>
                    
                </li>
                {% if user.is_authenticated %}
                <li><a href={% url 'users:details' %}>Hi {{ user.username }} </a></li>
                <li> <form class="navbar-form navbar-left" action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class=" white-text waves-effect waves-teal btn-flat">Logout</button>
                </form></li>
                {% else %}
                
                <!--These dont need to be forms so need to be converted at some point
                    Also, they need to be added to the mobile collapsed menu-->
                    <li><form  action="{% url 'users:signup' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="white-text waves-effect waves-red btn-flat">Create Account</button>
                    </form></li>
                    <li><form  action="{% url 'users:login' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="white-text waves-effect waves-red btn-flat">Login</button>
                    </form></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        
        <ul class="sidenav" id="mobile-nav">


            <li>{% with total_items=cart|length %}
                {% if cart|length > 0 %}
                
                <a href={% url 'cart:cart_detail' %}>
                    {{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }}
                </a>
                {% else %}
                Your cart is empty.
                {% endif %}
                {% endwith %}</li>
                
                <li>Search:
                    <form  style="float: right" role="search" method="get" action="{% url 'movies:index' %}">
                        <input type="text" name="q" value="{{ request.GET.q }}" style="color: black;float: right" />
                    </form>
                </li>
                {% if user.is_authenticated %}
                <li style="float: left"><a href={% url 'users:details' %}>Hi {{ user.username }} </a></li>
                <li> <form class="navbar-form navbar-left" action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class=" black-text waves-effect waves-teal btn-flat">Logout</button>
                </form>
            </li>
            {% else %}
            <li><form  action="{% url 'users:signup' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="black-text waves-effect waves-red btn-flat">Create Account</button>
            </form>
        </li>
        <li>
            <form  action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="black-text waves-effect waves-red btn-flat">Login</button>
            </form>
        </li>
        {% endif %}
        
        
        
    </ul>
    
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'movies/js/materialize.min.js' %}"></script>
    <script>
        $(document).ready(function(){
            $('.sidenav').sidenav();
        });
        $(document).ready(function(){
            $('.fixed-action-btn').floatingActionButton();
        });
    </script>
</body>
</html>

movies/templates/movies/base_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Notflix{% endblock %}</title>
    {% load staticfiles %}
<link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'movies/css/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>

<body>

<nav class="navbar navbar-inverse">
<div class="container-fluid">
    <!-- header-->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'movies:index' %}">Notflix</a>

    </div>

    <!-- items-->
    <div class="collapse navbar-collapse" id="topNavBar">
        <ul class="nav navbar-nav">
            <li class="{% block movies_active %}{% endblock %}"><a
                    href="{% url 'movies:index' %}">
                <span class="glyphicon glyphicon-film" aria-hidden="true">
                </span>&nbsp; Movies</a></li>

        </ul>

    <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'movies:index' %}">
        <div class="form-group">
            <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
    </form>

        {% if user.is_authenticated %}
            <ul class="nav navbar-nav">
            <li class="navbar-form navbar-right">Welcome {{ user.username }}!</li>
            </ul>
          <ul>
              <li>
                  <form class="navbar-form navbar-left" action="{% url 'users:logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-default">Logout</button>
                  </form>
              </li>
          </ul>
    {% else %}
            <ul class="nav navbar-nav">
                <li class="navbar-form navbar-right">Welcome Guest!</li>
            </ul>
            <form class="navbar-form navbar-left" action="{% url 'users:signup' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-default">Create Account</button>
            </form>
            <form class="navbar-form navbar-left" action="{% url 'users:login' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-default">Login</button>
            </form>


    {% endif %}


    </div>
</div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movies/templates/movies/create_movie.html
{% extends 'movies/base.html' %}
{% block title %}Add a New Movie{% endblock %}
{% block albums_active %}active{% endblock %}

movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% block title %}{{ movie }}{% endblock %}
{% block movies_active %}active{% endblock %}

{% block body %}
<div class="row">
    <div class="col s12 m6">
        <img id="detail-img" src="https://placeimg.com/640/480/any?cache={{ movie.id }}" >
    </div>
    <div class="col s12 m6">
        <h3>{{ movie.movie_title }}</h3>
        <div>
            <span class="badge new grey left" data-badge-caption="{{ movie.genre }}" style="margin-left: 0px;"></span>
            <span class="badge new grey left" data-badge-caption="£{{ movie.price }}"></span> <br>
        </div>
        <br>
        <div>
            <form action="{% url 'movies:like_movie' %}" method="post" style="display:inline;">
                {% csrf_token %}
                {% if is_liked %}
                    <button type="submit" name="movie_id" value="{{ movie.id }}" class="waves-effect waves-light btn">Remove Like</button>
                {% else %}
                    <button type="submit" name="movie_id" value="{{ movie.id }}" class="waves-effect waves-light btn green">Like</button>
                {% endif %}
            </form>
            <form action="{% url 'movies:dislike_movie' %}" method="post" style="display:inline;">
                {% csrf_token %}
                {% if is_disliked %}
                    <button type="submit" name="movie_id" value="{{ movie.id }}" class="waves-effect waves-light btn" >Remove Dislike</button>
                {% else %}
                    <button type="submit" name="movie_id" value="{{ movie.id }}" class="waves-effect waves-light btn red">Dislike</button>
                {% endif %}
            </form>
            
              - {{ total_likes }} Like{{ total_likes|pluralize }}
            {{ total_dislikes }} Dislike{{ total_dislikes|pluralize }}
        </div>
        <div><br>{{ movie.description }}<br>


            <form action="{% url 'cart:cart_add' movie.id %}" method="post" style="display:inline;">
                {{cart_movie_form}}
                {% csrf_token %}
                <br>
                <button type="submit" class="btn #f44336 red"><i class="material-icons">add_shopping_cart</i> Add to Cart</button>
            </form></div>
    </div>
</div>
<h3>Add your review</h3>

        <form action="{% url 'movies:add_review' movie.id %}" method="post" style="display:inline;">
            {{ form }}
            {% csrf_token %}

            <br>
            <button type="submit" class="btn #f44336 red"><i class="material-icons"></i> Add Review</button>
        </form>

    {% if movie.review_set.all %}
            <h5>{{ movie.average_rating }} average rating</h5>

        <div class="row">
            {% for review in movie.review_set.all %}
                <div class="col-xs-6 col-lg-4">
                    <h5>{{ review.user_name }}</h5>
                    <h6>Rated {{ review.rating }} out of 5</h6>
                    <h6>Comment: {{ review.comment }}</h6>
{#                    <h6>Rated {{ review.rating }} of 5 by <a href="{% url 'movies:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h6>#}
{#                    <h5><a href="{% url 'movies:review_detail' review.id %}">#}
{#                        Read more#}
{#                    </a></h5>#}
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No reviews for this movie yet</p>
    {% endif %}



{% endblock %}

movies/templates/movies/index.html
{% extends 'movies/base.html' %}
{% block body %}
<div class="row wrapper">
    <div class="col s12 m2 pushpin side">
        
        {% comment %} <h3>Genres</h3> {% endcomment %}
        <ul class="">
            <li {% if not genre %}class="selected" {% endif %}>
                <a href="{% url "movies:index" %}">All</a>
            </li>
            {% for c in genres %}
            <a href="{{ c.name }}">{{ c.name }}</a>
            <li {% if genre.slug == c.slug %}class="selected" {% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c }}</a>
            </li>
            {% endfor %}
        </ul>
        <!-- Dropdown Trigger -->
        <a class='dropdown-trigger btn red' href='#' data-target='dropdown1'>Sort</a>
        <!-- Dropdown Structure -->
        <ul id='dropdown1' class='dropdown-content'>
            <li> <a href="{% url 'movies:sort_name_asc'  %}"><i class="material-icons">keyboard_arrow_up</i>Name</a></li>
            <li><a href="{% url 'movies:sort_name_dsc'  %}"><i class="material-icons">keyboard_arrow_down</i>Name</a></li>
            
            <li> <a href="{% url 'movies:sort_price_asc'  %}"><i class="material-icons">keyboard_arrow_up</i>Price</a></li>
            <li><a href="{% url 'movies:sort_price_dsc'  %}"><i class="material-icons">keyboard_arrow_down</i>Price</a></li>
            
            <li> <a href="{% url 'movies:sort_date_asc'  %}"><i class="material-icons">keyboard_arrow_up</i>Date</a></li>
            <li><a href="{% url 'movies:sort_date_dsc'  %}"><i class="material-icons">keyboard_arrow_down</i>Date</a></li>
        </ul>
        
    </div>
    <div class="col s12 m10 offset-m2">
        <div class="main">
            {% comment %} <h2>Movies </h2> {% endcomment %}
            {% if movies %}
            <div class="row">
                {% for movie in movies %}
                <div class="col s12 m7 l6">
                    <div class="card large">
                        <div class="card-image">
                            {% comment %} <a href="{% url 'movies:detail' movie.id %}"><img class="index-img" src="{{ movie.movie_logo.url }}" > </a> {% endcomment %}
                            <a href="{% url 'movies:detail' movie.id %}"><img class="index-img" src="https://placeimg.com/640/480/any?cache={{ movie.id }}" > </a>

                        </div>
                        
                        <div class="card-content">
                            <span class="card-title truncate">{{ movie.movie_title }} <span class="badge new red" data-badge-caption="£{{ movie.price }}"></span></span>
                            <p class="truncate">{{ movie.description }}</p>
                            <p class="truncate">{{ movie.genre }}</p>
                        </div>
                        <div class="card-action">
                            <a href="{% url 'movies:detail' movie.id %}">Go to Movie</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <div>
                <br>
                <a href="{% url 'movies:create_movie' %}">
                    <button type="button" class="btn red waves-effect waves-light">
                        <span></span>&nbsp; Add a Movie
                    </button>
                </a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<div class="pagination">
    <span class="step-links">
        {% if movies.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ movies.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ movies.number }} of {{ movies.paginator.num_pages }}.
        </span>

        {% if movies.has_next %}
            <a href="?page={{ movies.next_page_number }}">next</a>
            <a href="?page={{ movies.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
    

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.dropdown-trigger');
        var instances = M.Dropdown.init(elems, {});
    });
    
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.pushpin');
        var instances = M.Pushpin.init(elems, {offset: 100});
    });
</script>
{% endblock %}

movies/templates/movies/movie_upload.html
{% extends 'movies/base.html' %}
{% block body %}
{% if messages %}

    {% for message in messages %}
        <div> {{ message|safe}}</div>
    {% endfor %}
{% else %}
    {{ order }}
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label>Upload file</label>
    <input type="file" name="file">
    <p>only csv files</p>
    <button type="submit">Upload</button>
    </form>
{% endif %}
{% endblock %}