cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<movie_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<movie_id>\d+)/$', views.cart_remove, name='cart_remove'),
    url(r'^clear/$', views.cart_clear, name='cart_clear'),

]

notflix/urls.py
"""The master router for the whole project
"""

from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from adminplus.sites import AdminSitePlus

# Admin setup
admin.site = AdminSitePlus()
admin.autodiscover()


urlpatterns = [
    url(r'^notflixadmin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^stats/', include('stats.urls', namespace='stats')),
    url(r'^', include('movies.urls', namespace='movies')),
   #url(r'^users/', include('users.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testImport/testImport/urls.py
from django.conf.urls import url
from django.contrib import admin
from adminplus.sites import AdminSitePlus

# Admin setup
admin.site = AdminSitePlus()
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

users/urls.py
"""Authenitcation URLs
"""

from django.conf.urls import url, include
from . import views
from . import views as core_views
from django.contrib.auth import views as auth_views
from django.urls import reverse

app_name = 'users'

urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^signup/$', core_views.signup_view, name='signup'),
    url(r'^details/$', views.detail_view, name='details'),
    url(r'^password/$', views.change_password, name='change_password'),

]

users/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime


class Profile(models.Model):
    FAVORITE_GENRE_CHOICES = (
        ('comedy', 'Comedy'),
        ('horror', 'Horror'),
        ('all', 'All'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=250)
    city = models.CharField(max_length=30)
    postcode = models.CharField(max_length=30)
    date_birth = models.DateField(default=datetime.date.today, blank=True)
    # preferred_genre = models.TextField(blank=False)
    preferred_genre = models.CharField(
        max_length=30,
        choices=FAVORITE_GENRE_CHOICES,
    )


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

users/forms.py
# adpated from https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html
from django.contrib.auth import login, authenticate
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField

FAVORITE_GENRE_CHOICES = (
    ('comedy', 'Comedy'),
    ('horror', 'Horror'),
    ('all', 'All'),
)


class DateInput(forms.DateInput):
    input_type = 'date'

class ChoiceInput(forms.ChoiceField):
    input_type = 'choice'

class SignUpForm(UserCreationForm):

    address = forms.CharField(max_length=250)
    city = forms.CharField(max_length=30)
    postcode = forms.CharField(max_length=30, help_text='postcode field')
    date_birth = forms.DateField()
    # preferred_genre = forms.ChoiceField(choices=FAVORITE_GENRE_CHOICES, widget=forms.RadioSelect)

    # date_birth=fields.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'address',
                  'city', 'postcode', )
        widgets = {
            'date_birth': DateInput(),
            # 'preferred_genre': ChoiceInput()

        }

users/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import SignUpForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages

from django.contrib.auth import update_session_auth_hash
from orders.models import OrderItem, Order



def signup_view(request):
    """The view that handles sign ups

    Arguments:
        request {request} -- The request

    Returns:
        render -- The sign up form or a redirect to the index
    """

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.address = form.cleaned_data.get('address')
            user.profile.city = form.cleaned_data.get('city')
            user.profile.postcode = form.cleaned_data.get('postcode')
            user.profile.date_birth = form.cleaned_data.get('date_birth')
            # user.profile.preferred_genre = form.cleaned_data.get('preferred_genre')
            user.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()

    return render(request, 'users/signup.html', {'form': form})


def login_view(request):
    """The view that handles logins

    Arguments:
        request {request} -- The request

    Returns:
        render -- The login form or the index is the attempt is successfull
    """
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # login the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))

            return redirect('movies:index')

    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    """The view that handles logouts

    Arguments:
        request {request} -- The request

    Returns:
        render -- The logged out page
    """
    if request.method == 'POST':
        logout(request)
        return render(request, 'users/logout.html')

def detail_view(request):
    movie_order = OrderItem.objects.all()
    user_order = Order.objects.all()



    return render(request, 'users/user_details.html', {'movie_order': movie_order, 'user_order':user_order})

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return render(request, 'users/password_changed.html')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'users/password_change.html', {
        'form': form
    })

users/templates/users/login.html
{% extends 'movies/base.html' %}

{% block body %}
{#  <h2>Login</h2>#}
{#  <form class="site-form" action="{% url 'users:login' %}" method="post">#}
{#    {% csrf_token %}#}
{#    {{ form }}#}
{#      {% if request.GET.next %}#}
{#           <p>Your account doesn't have access to this page. To proceed,#}
{#      please login with an account that has access.</p>#}
{#        <input type="hidden" name="next" value="{{ request.GET.next }}">#}
{#      {% endif %}#}
{#    <input type="submit" value="Login"> </input>#}
{#  </form>#}

<div class="row">
    <div class="col s12 m6 l4 offset-m3 offset-l4">
        <div>
            <h3>Login</h3>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="center-align">
                    
                    <input type="submit" value="Login" class="btn red">
                </div>                
            </form>
        </div>
        <div class="card-panel signup z-depth-1">
            <form action="{% url 'users:signup'%}"><br>
                <div class="center-align">
                        <h3>New Customer?</h3>
                <input type="submit" value="Sign up" class="btn red"/>

            </div>    
        </form>
        
        </div>
    </div>
    <!-- <div class="col s12 m5 l4">

    </div> -->
</div>
{% endblock %}

users/templates/users/logout.html
{% extends "movies/base.html" %}

{% block body %}
<p>Your are logged out!</p>

<p><a href="{% url 'users:login'%}">Click here to log in again.</a></p>


{% endblock %}

users/templates/users/password_change.html
{% extends 'movies/base.html' %}

{% block body %}
  <h2>Change Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change Password</button>
  </form>
{% endblock %}

users/templates/users/password_changed.html
{% extends 'movies/base.html' %}

{% block body %}
  <h2>Password Changed</h2>
{% endblock %}

users/templates/users/signup.html
{% extends 'movies/base.html' %}

{% block body %}
<div class="row">
  <div class="col s12 m6 offset-m3">
    <h2>Registration</h2>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
  <p>
    {{ field.label_tag }}<br>
    {{ field }}
    {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
  </p>
  {% endfor %}
  
  <p><input type="submit" value="Register" class="btn red"></p>
</form>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('#id_date_birth');
    var instances = M.Datepicker.init(elems, {
      'format': 'yyyy-mm-dd',
      'defaultDate': new Date("January 31 2000 12:30"),
      'yearRange': 50,
      'maxDate': new Date()
    });
  });
  
</script>
{% endblock %}

users/templates/users/user_details.html
{% extends "movies/base.html" %}

{% block body %}
    <h3>Profile Details</h3>
<p>{{ user.first_name }} {{ user.last_name }}</p>
    <p>{{ user.profile.address }}</p>
    <p>{{ user.profile.city }},</p>
    <p>{{ user.profile.postcode }} </p>
    <p>{{ user.profile.date_birth }}</p>
     <p>{{ user.profile.preferred_genre }}</p>
<form action="{% url 'users:change_password'%}"><br>

    <input type="submit" value="Change Password" />

</form>
<h3>Order History</h3>
{% for i in user_order %}
    {% if i.user == user %}
        {%  for i in movie_order|slice:":1" %}
                {{ i.movie}}
        {% endfor %}
    {% endif %}

    {% endfor %}



{% endblock %}